# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Your Awesome Site
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _sass
    style: :compressed

exclude: ['node_modules', 'bower_components']

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

theme:
    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
    cdn:
      bootstrap: true
      fontawesome: true
      jquery: true
      bootstrapjs: true

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 

# ----------------------- #
# Google Analytics
# ----------------------- #
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking
